package gestionlibrairie;

import java.text.SimpleDateFormat;
import java.util.Calendar;

public class Accueil extends javax.swing.JFrame {

    /**
     * Creates new form Accueil
     */
    
    public Accueil() {
        initComponents();
        
        //Afficher l'heure et la date
        Calendar currentDate = Calendar.getInstance();
        SimpleDateFormat dat= new SimpleDateFormat("yyyy/MMMMMMMM/dd");
        SimpleDateFormat heure= new SimpleDateFormat("HH:mm:ss");
        String actualDate = dat.format(currentDate.getTime());
        String actualHour = heure.format(currentDate.getTime());
        labelDate.setText(actualDate);
        labelHeure.setText(actualHour);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonRechercher = new javax.swing.JButton();
        buttonEnregistrer = new javax.swing.JButton();
        labelDate = new javax.swing.JLabel();
        labelHeure = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Accueil");
        setBackground(new java.awt.Color(255, 51, 51));

        buttonRechercher.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonRechercher.setText("Rechercher un livre");
        buttonRechercher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRechercherMouseClicked(evt);
            }
        });

        buttonEnregistrer.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonEnregistrer.setText("Enregistrer un livre");
        buttonEnregistrer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEnregistrerMouseClicked(evt);
            }
        });

        labelHeure.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonRechercher)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelHeure, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                        .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(buttonEnregistrer)
                    .addContainerGap(247, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeure, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(buttonRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(142, Short.MAX_VALUE)
                    .addComponent(buttonEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(90, 90, 90)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Action à faire lors du clic du bouton Enregistrer
    private void buttonEnregistrerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEnregistrerMouseClicked
        //Fermer l'actuelle fenêtre
        this.dispose();
        
        //Afficher une nouvelle fenêtre d'Enregistrement
        Enregistrement enregistrement =  new Enregistrement();
        enregistrement.setVisible(true);
    }//GEN-LAST:event_buttonEnregistrerMouseClicked

    //Action à faire lors du clic du bouton Enregistrer
    private void buttonRechercherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRechercherMouseClicked
        //Fermer l'actuelle fenêtre
        this.dispose();
        
        //Afficher une nouvelle fenêtre de Recherche
        Recherche recherche =  new Recherche();
        recherche.setVisible(true);
    }//GEN-LAST:event_buttonRechercherMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEnregistrer;
    private javax.swing.JButton buttonRechercher;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelHeure;
    // End of variables declaration//GEN-END:variables
}
