/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionlibrairie;

import javax.swing.JFrame;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import java.awt.*;
import java.awt.event.*;
import java.io.File;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author hp
 */
public class Enregistrement extends javax.swing.JFrame {
    
    
    //String sTitre, sAuteur, sEdition, sParution, sPages;

    /**
     * Creates new form Enregistrement
     */
    public Enregistrement (){
        initComponents();
        
        
    }
/*
    private Enregistrement() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAuteur = new javax.swing.JLabel();
        labelTitre = new javax.swing.JLabel();
        labelEdition = new javax.swing.JLabel();
        labelParution = new javax.swing.JLabel();
        labelPages = new javax.swing.JLabel();
        labelModule = new javax.swing.JLabel();
        fieldAuteur = new javax.swing.JTextField();
        fieldTitre = new javax.swing.JTextField();
        fieldEdition = new javax.swing.JTextField();
        fieldParution = new javax.swing.JTextField();
        fieldPages = new javax.swing.JTextField();
        buttonRechercher = new javax.swing.JButton();
        buttonEnregistrer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enregistrement d'un livre");

        labelAuteur.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelAuteur.setText("Auteur : ");

        labelTitre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelTitre.setText("Titre :");

        labelEdition.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelEdition.setText("Maison d'édition :");

        labelParution.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelParution.setText("Date de parution :");

        labelPages.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelPages.setText("Nombre de pages  :");

        labelModule.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelModule.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModule.setText("ENREGISTREMENT LIVRE");

        fieldAuteur.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        fieldTitre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        fieldEdition.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        fieldParution.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        fieldPages.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        buttonRechercher.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonRechercher.setText("Retour");
        buttonRechercher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRechercherMouseClicked(evt);
            }
        });

        buttonEnregistrer.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonEnregistrer.setText("Enregistrer");
        buttonEnregistrer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEnregistrerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fieldTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAuteur, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelParution, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPages, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(fieldEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldAuteur, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldParution, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldPages, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(labelModule, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(buttonEnregistrer)
                .addGap(115, 115, 115))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(labelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(389, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelModule, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAuteur, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldAuteur, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelParution, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldParution, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPages, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPages, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonRechercher, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(buttonEnregistrer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(76, 76, 76)
                    .addComponent(labelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(321, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEnregistrerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEnregistrerMouseClicked
        // Action à faire lors du clic du bouton Enregistrer
        
        String sTitre = null, sAuteur = null, sEdition = null, sParution = null, sPages = null;
        String sqlRequete;
        
        //Récupérer les données saisies
        sTitre = fieldTitre.getText();
        sAuteur = fieldAuteur.getText();
        sEdition = fieldEdition.getText();
        sParution = fieldParution.getText();
        sPages = fieldPages.getText();
        
        //Définir la requete d'insertion à la base de données
        sqlRequete = "insert into livre(titre,auteur,edition,parution,pages) values('" + sTitre + "','" + sAuteur + "','" + sEdition + "','" + sParution + "','" + sPages + "')";
        try {
            //Créer une session de connexion à la base de données
            Statement stmt = Connexion.conn.createStatement();
            //Insertion des données saisies dans la base de données
            stmt.executeUpdate(sqlRequete);
            //Afficher un message en cas d'insertion
            JOptionPane.showMessageDialog(this, "Les données ont été enregistrées!!", " ", JOptionPane.WARNING_MESSAGE);
        } catch (SQLException ex) {
            //Afficher un message d'erreur en cas de non-insertion
            JOptionPane.showMessageDialog(this, "Les données n'ont pas pu être enregistrées, veuillez réessayer!!", "Erreur !!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buttonEnregistrerMouseClicked
    
    // Action à faire lors du clic du bouton Retour
    private void buttonRechercherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRechercherMouseClicked
        
        //Fermer l'actuelle fenêtre
        this.dispose();
        
        //Afficher une nouvelle fenêtre d'Accueil
        Accueil accueil =  new Accueil();
        accueil.setVisible(true);
        
    }//GEN-LAST:event_buttonRechercherMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enregistrement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enregistrement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enregistrement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enregistrement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //Connexion à la base de données
        Connexion conn =  new Connexion();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Enregistrement().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEnregistrer;
    private javax.swing.JButton buttonRechercher;
    private javax.swing.JTextField fieldAuteur;
    private javax.swing.JTextField fieldEdition;
    private javax.swing.JTextField fieldPages;
    private javax.swing.JTextField fieldParution;
    private javax.swing.JTextField fieldTitre;
    private javax.swing.JLabel labelAuteur;
    private javax.swing.JLabel labelEdition;
    private javax.swing.JLabel labelModule;
    private javax.swing.JLabel labelPages;
    private javax.swing.JLabel labelParution;
    private javax.swing.JLabel labelTitre;
    // End of variables declaration//GEN-END:variables
}
