/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionlibrairie;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Recherche extends javax.swing.JFrame {

    /**
     * Creates new form Enregistrement
     */
    public Recherche() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitre = new javax.swing.JLabel();
        labelModule = new javax.swing.JLabel();
        fieldTitre = new javax.swing.JTextField();
        buttonRechercher = new javax.swing.JButton();
        buttonRetour = new javax.swing.JButton();
        labelAuteur = new javax.swing.JLabel();
        labelEdition = new javax.swing.JLabel();
        labelParution = new javax.swing.JLabel();
        labelPages = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recherche d'un livre");
        setBackground(new java.awt.Color(255, 255, 255));

        labelTitre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelTitre.setText("Titre :");

        labelModule.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelModule.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelModule.setText("Recherche LIVRE");

        fieldTitre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        buttonRechercher.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonRechercher.setText("Rechercher");
        buttonRechercher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRechercherMouseClicked(evt);
            }
        });

        buttonRetour.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonRetour.setText("Retour");
        buttonRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRetourMouseClicked(evt);
            }
        });

        labelAuteur.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        labelEdition.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        labelParution.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        labelPages.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelModule, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fieldTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(buttonRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelParution, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelEdition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAuteur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelPages, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(labelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(389, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelModule, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldTitre, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(buttonRechercher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(labelAuteur, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelParution, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPages, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(buttonRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(76, 76, 76)
                    .addComponent(labelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(247, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRechercherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRechercherMouseClicked
        // Action à faire lors du clic du bouton Enregistrer
        
        //Déclarer les variables
        String sTitre = null, sAuteur = null, sEdition = null, sParution = null, sPages = null;
        String sqlRequete;
        
        //Récupérer le titre saisi
        sTitre = fieldTitre.getText();
        try {
            //Créer une session de connexion à la base de données
            Statement stmt = Connexion.conn.createStatement();
            //Définir la requete de recherche dans la base de données
            sqlRequete = "select * from livre where titre = '" + sTitre + "' ";
            //Exécuter la requete de recherche dans la base de données
            ResultSet rs = stmt.executeQuery(sqlRequete);
            //Récupérer le premier élément 
            rs.first();
            
            //Récupérer les infos du livre souhaité de la base de données 
            sAuteur = rs.getString(2);
            sEdition = rs.getString(3);
            sParution = rs.getString(4);
            sPages = rs.getString(5);
            
            //Afficher les infos liées au titre saisi
            labelAuteur.setText(sAuteur);
            labelEdition.setText(sEdition);
            labelParution.setText(sParution);
            labelPages.setText(sPages);
        } catch (SQLException ex) {
            //Vider les champs au cas où une recherche positive a été faite ultérieurement
            labelAuteur.setText("");
            labelEdition.setText("");
            labelParution.setText("");
            labelPages.setText("");
            
            //Afficher un message si le livre n'est pas trouvé
            JOptionPane.showMessageDialog(this, "Le livre introuvé !!!, vérifiez le titre saisi!!", "Erreur !!", JOptionPane.WARNING_MESSAGE);
        }
       
        
        
        
        
        
    }//GEN-LAST:event_buttonRechercherMouseClicked

    // Action à faire lors du clic du bouton Retour
    private void buttonRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRetourMouseClicked
 
        //Fermer l'actuelle fenêtre
        this.dispose();
        
        //Afficher une nouvelle fenêtre d'Accueil
        Accueil accueil =  new Accueil();
        accueil.setVisible(true);
        
    }//GEN-LAST:event_buttonRetourMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recherche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recherche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recherche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recherche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //Connexion à la base de données
        Connexion conn =  new Connexion();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recherche().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonRechercher;
    private javax.swing.JButton buttonRetour;
    private javax.swing.JTextField fieldTitre;
    private javax.swing.JLabel labelAuteur;
    private javax.swing.JLabel labelEdition;
    private javax.swing.JLabel labelModule;
    private javax.swing.JLabel labelPages;
    private javax.swing.JLabel labelParution;
    private javax.swing.JLabel labelTitre;
    // End of variables declaration//GEN-END:variables
}
